<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('users')->insert([
            [
                'id'=>1,
                'nama_depan' => 'John',
                'nama_belakang' => 'Doe',
                'email' => 'john.doe@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>2,
                'nama_depan' => 'Jane',
                'nama_belakang' => 'Smith',
                'email' => 'jane.smith@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>3,
                'nama_depan' => 'Staff Kemahasiswaan',
                'nama_belakang' => 'Satu',
                'email' => 'staffkema.satu@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>4,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Sipil',
                'email' => 'kajur.sipil@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>5,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Mesin',
                'email' => 'kajur.mesin@polban.ac.id',
                'jenis_kelamin' => 'Wanita',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>6,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Refrigerasi dan Tata Udara',
                'email' => 'kajur.refri@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Konversi Energi',
                'email' => 'kajur.konversi@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Elektro',
                'email' => 'kajur.elektro@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Kimia',
                'email' => 'kajur.kimia@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Teknik Komputer dan Informatika',
                'email' => 'kajur.kominfo@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Akuntansi',
                'email' => 'kajur.akuntansi@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Administrasi Niaga',
                'email' => 'kajur.niaga@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'nama_depan' => 'Kepala Jurusan',
                'nama_belakang' => 'Bahasa Inggris',
                'email' => 'kajur.inggris@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'=>14,
                'nama_depan' => 'Koordinator Layanan Eksternal',
                'nama_belakang' => 'Satu',
                'email' => 'kle.satu@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>15,
                'nama_depan' => 'Wakil Direktur',
                'nama_belakang' => 'Tiga',
                'email' => 'wd.tiga@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>16,
                'nama_depan' => 'Tresnardi',
                'nama_belakang' => 'Fathu Rhamdan',
                'email' => 'tresnardi.fathu.tif23@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>17,
                'nama_depan' => 'Daffa',
                'nama_belakang' => 'Al Ghifari',
                'email' => 'daffa.al.tif23@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>18,
                'nama_depan' => 'Daiva',
                'nama_belakang' => 'Raditya Pradipa',
                'email' => 'daiva.raditya.tif23@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>19,
                'nama_depan' => 'Muhammad',
                'nama_belakang' => 'Raihan Pratama',
                'email' => 'muhammad.raihan.tif23@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>20,
                'nama_depan' => 'R',
                'nama_belakang' => 'Muhammad Farrel Walid Imtiyaaz',
                'email' => 'r.muhammad.tif23@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=>100,
                'nama_depan' => 'Dummy',
                'nama_belakang' => 'Dummy',
                'email' => 'dummy@polban.ac.id',
                'jenis_kelamin' => 'Pria',
                'foto' => 'example.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}